# Generated by Django 4.0.4 on 2022-06-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przystanek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa przystanku')),
                ('opis', models.CharField(blank=True, max_length=100, verbose_name='Dodatkowy opis')),
            ],
            options={
                'verbose_name_plural': 'przystanki',
            },
        ),
        migrations.CreateModel(
            name='Rozklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa rozkładu')),
                ('na_stronie', models.BooleanField(default=False, verbose_name='Aktualnie w internecie')),
                ('od', models.DateField(blank=True)),
                ('do', models.DateField(blank=True)),
                ('description', models.TextField(blank=True, verbose_name='Komentarz')),
            ],
            options={
                'verbose_name_plural': 'rozkłady',
            },
        ),
        migrations.CreateModel(
            name='Godzina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godzina', models.TimeField(verbose_name='Godzina')),
                ('powrot', models.BooleanField(blank=True, default=False, verbose_name='powrót')),
                ('sobota', models.BooleanField(default=False, verbose_name='kursuje w soboty')),
                ('zjazd_do_skotnik', models.BooleanField(default=False, verbose_name='zjazd do Skotnik')),
                ('przystanek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazda.przystanek')),
                ('rozklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazda.rozklad')),
            ],
            options={
                'verbose_name_plural': 'godziny',
                'ordering': ['godzina'],
            },
        ),
    ]
