# Generated by Django 4.0.4 on 2022-06-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godzina',
            name='rozklad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jazda.rozklad'),
        ),
    ]
