# Generated by Django 4.0.4 on 2022-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0003_przystanek_opis_drugi_alter_przystanek_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='godzina',
            name='czarne',
            field=models.BooleanField(default=False, verbose_name='czarne'),
        ),
        migrations.AddField(
            model_name='godzina',
            name='gwda',
            field=models.BooleanField(default=False, verbose_name='gwda'),
        ),
        migrations.AddField(
            model_name='godzina',
            name='szek',
            field=models.BooleanField(default=False, verbose_name='szek'),
        ),
    ]
