# Generated by Django 4.0.4 on 2022-07-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0004_godzina_czarne_godzina_gwda_godzina_szek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, verbose_name='Nazwa miasta')),
                ('opis', models.CharField(blank=True, max_length=100, verbose_name='Opis miasta')),
            ],
            options={
                'verbose_name_plural': 'miasta',
            },
        ),
        migrations.RemoveField(
            model_name='godzina',
            name='czarne',
        ),
        migrations.RemoveField(
            model_name='godzina',
            name='gwda',
        ),
        migrations.RemoveField(
            model_name='godzina',
            name='szek',
        ),
        migrations.AddField(
            model_name='przystanek',
            name='miasto',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='jazda.miasto'),
        ),
    ]
