# Generated by Django 4.0.4 on 2022-07-30 18:57

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0005_miasto_remove_godzina_czarne_remove_godzina_gwda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='przystanek',
            options={'ordering': ['miasto'], 'verbose_name_plural': 'przystanki'},
        ),
        migrations.AlterField(
            model_name='godzina',
            name='rozklad',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='jazda.rozklad'),
        ),
        migrations.AlterField(
            model_name='przystanek',
            name='miasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazda.miasto'),
        ),
    ]
