# Generated by Django 4.0.4 on 2022-07-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0006_lokalizacja_alter_przystanek_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lokalizacja',
            options={'verbose_name_plural': 'lokalizacje'},
        ),
    ]
