# Generated by Django 4.0.4 on 2022-07-30 19:20

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0007_alter_lokalizacja_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokalizacja',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='lokalizacja',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, verbose_name='Namiary'),
        ),
    ]
