# Generated by Django 4.0.4 on 2022-08-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0008_alter_lokalizacja_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lokalizacja',
        ),
    ]
