# Generated by Django 4.0.4 on 2022-08-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0009_delete_lokalizacja'),
    ]

    operations = [
        migrations.AddField(
            model_name='przystanek',
            name='dlugosc',
            field=models.FloatField(blank=True, default=False, verbose_name='Długość'),
        ),
        migrations.AddField(
            model_name='przystanek',
            name='szerokosc',
            field=models.FloatField(blank=True, default=False, verbose_name='Szerokość'),
        ),
    ]
