# Generated by Django 4.0.4 on 2022-08-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0011_alter_przystanek_dlugosc_alter_przystanek_szerokosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przystanek',
            name='dlugosc',
            field=models.FloatField(verbose_name='Dł. geograficzna'),
        ),
        migrations.AlterField(
            model_name='przystanek',
            name='szerokosc',
            field=models.FloatField(verbose_name='Szer. geograficzna'),
        ),
    ]
