# Generated by Django 4.0.4 on 2022-08-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazda', '0012_alter_przystanek_dlugosc_alter_przystanek_szerokosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godzina',
            name='rozklad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazda.rozklad'),
        ),
    ]
